---

- name: Configure Supervisor service
  ansible.builtin.template:
    src: supervisor.service.j2
    dest: /etc/systemd/system/supervisor.service
    mode: '755'
  become: '{{ do_become }}'
  notify:
    - reload systemd
    - restart supervisor
  tags: [supervisor, config] # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882

...
