---

- name: Install Supervisor service
  ansible.builtin.template:
    src: supervisor
    dest: /etc/init.d/supervisor
    mode: '755'
  become: '{{ do_become }}'
  notify: restart supervisor
  tags: [supervisor, config] # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882

...
