---

- name: reload systemd
  ansible.builtin.command:
    systemctl daemon-reload
  become: '{{ do_become }}'

- name: restart supervisor
  ansible.builtin.service:
    name: supervisor
    state: restarted
    use: '{{ supervisor_daemon_mode }}'
  become: '{{ do_become }}'

...
